import {
    Sparkles,
  Check,
  Trash2,
  ImageIcon,
  Mic,
  Menu,
  Play,
} from "lucide-react";



export default function MemorialContributionApproval({contributors}) {
    const gallery = [1, 2, 3, 4, 5];

    return (
    <div className="mx-auto max-w-7xl">
        {/* Header Cards */}
        <div className="grid grid-cols-[320px_1fr] gap-3">
          {/* User Card */}
          <div className="rounded-md border border-gray-300 bg-white p-5">
            <div className="flex items-center gap-4">
              <div className="h-16 w-16 rounded-full bg-gray-300" />

              <div>
                <h2 className="text-sm font-semibold">{contributors.user}</h2>

                <p className="text-xs text-gray-600">{contributors.contribution}</p>

                <p className="mt-1 text-[11px] text-gray-500">
                  Last submitted May 20, 2026
                </p>

                <div className="mt-3 inline-flex rounded-md bg-gray-200 px-4 py-1 text-xs text-gray-700">
                  Relationship
                </div>
              </div>
            </div>
          </div>

          {/* AI Summary */}
          <div className="flex min-h-[122px] flex-col justify-between rounded-md border border-gray-300 bg-white p-5">
            <div className="flex gap-3">
              <Sparkles className="mt-1" size={18} />

              <p className="max-w-3xl text-sm text-gray-700">
                {contributors.summary}
              </p>
            </div>

            <div className="mt-6 flex items-center justify-between">
              <p className="text-xs text-gray-600">Approve submission?</p>

              <div className="flex items-center gap-5">
                <button className="text-black transition hover:scale-110">
                  <Check size={20} />
                </button>

                <button className="text-black transition hover:scale-110">
                  <Trash2 size={20} />
                </button>
              </div>
            </div>
          </div>
        </div>


     {/* Photo Contribution */}
        <section className="mt-5 rounded-md border border-gray-300 bg-white p-4">
          <div className="mb-4 flex items-start gap-3">
            <div className="mt-1 rounded bg-black p-1 text-white">
              <Menu size={12} />
            </div>

            <div>
              <p className="text-xs font-medium">
                {contributors.user} added 5 photos
              </p>

              <p className="text-[11px] text-gray-500">
                Submitted May 1, 2026
              </p>
            </div>
          </div>
            <div className="ml-[240px]">
                <div className="grid max-w-[520px] grid-cols-3 gap-3">
                    {gallery.map((item) => (
                    <div
                        key={item}
                        className="aspect-square rounded-sm bg-gray-300"
                    />
                    ))}
                </div>
            </div>

        </section>

        {/* Audio Contribution */}
        <section className="mt-5 rounded-md border border-gray-300 bg-white p-4">
          <div className="flex items-start justify-between">
            <div className="flex gap-3">
              <Mic className="mt-1" size={18} />

              <div>
                <p className="text-xs font-medium">
                  {contributors.user} added 1 audio
                </p>

                <p className="text-[11px] text-gray-500">
                  Submitted May 1, 2026
                </p>
              </div>
            </div>

            <div className="mr-4 flex items-center gap-4">
              <button className="flex h-9 w-9 items-center justify-center rounded-full bg-black text-white">
                <Play size={15} fill="white" />
              </button>

              <div className="flex items-center gap-[2px]">
                {Array.from({ length: 24 }).map((_, i) => (
                  <div
                    key={i}
                    className="w-[3px] rounded-full bg-black"
                    style={{
                      height: `${10 + ((i * 7) % 24)}px`,
                    }}
                  />
                ))}
              </div>
            </div>

            <p className="max-w-md text-sm italic text-gray-600">
              “When played, an audio transcript generated by AI will play
              alongside the audio. It’ll look something like this.”
            </p>
          </div>
        </section>

        {/* Story Contribution */}
        <section className="mt-5 rounded-md border border-gray-300 bg-white p-4">
          <div className="flex items-start gap-3">
            <Menu className="mt-1" size={18} />

            <div className="min-w-[180px]">
              <p className="text-xs font-medium">
                {contributors.user} added 1 story
              </p>

              <p className="text-[11px] text-gray-500">
                Submitted May 1, 2026
              </p>
            </div>

            <div>
              <h3 className="text-base font-semibold">Story Title</h3>

              <p className="mt-1 text-sm text-gray-600">
                An AI generated summary of the story will be featured here.
              </p>
            </div>
          </div>
        </section>
      </div>
  );
}
